import "./globals.css";
import type { Metadata } from "next";
import Providers from "./providers";
import ThemeButton from "./components/ThemeButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <header>
            <nav>
              <ul>
                <li>
                  <a href="/">Home</a>
                </li>
              </ul>
              <ThemeButton />
            </nav>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
