import "./globals.css";
import type { Metadata } from "next";
import Providers from "./providers";
import Main from "./containers/Main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex h-screen flex-col items-center justify-center bg-lightBg font-primary purple:bg-purpleBg dark:bg-darkBg ">
        <Providers>
          <Main />
          {children}
        </Providers>
      </body>
    </html>
  );
}
